package ru.illarionovroman.yandexmobilizationhomework.utils;


public class AppConstants {

    public static final String LANGUAGE_SPLIT_SYMBOL = ":";

    public static final String LANGS_EN = "\"af\":\"Afrikaans\",\"am\":\"Amharic\",\"ar\":\"Arabic\",\"az\":\"Azerbaijani\",\"ba\":\"Bashkir\",\"be\":\"Belarusian\",\"bg\":\"Bulgarian\",\"bn\":\"Bengali\",\"bs\":\"Bosnian\",\"ca\":\"Catalan\",\"ceb\":\"Cebuano\",\"cs\":\"Czech\",\"cy\":\"Welsh\",\"da\":\"Danish\",\"de\":\"German\",\"el\":\"Greek\",\"en\":\"English\",\"eo\":\"Esperanto\",\"es\":\"Spanish\",\"et\":\"Estonian\",\"eu\":\"Basque\",\"fa\":\"Persian\",\"fi\":\"Finnish\",\"fr\":\"French\",\"ga\":\"Irish\",\"gd\":\"Scottish Gaelic\",\"gl\":\"Galician\",\"gu\":\"Gujarati\",\"he\":\"Hebrew\",\"hi\":\"Hindi\",\"hr\":\"Croatian\",\"ht\":\"Haitian\",\"hu\":\"Hungarian\",\"hy\":\"Armenian\",\"id\":\"Indonesian\",\"is\":\"Icelandic\",\"it\":\"Italian\",\"ja\":\"Japanese\",\"jv\":\"Javanese\",\"ka\":\"Georgian\",\"kk\":\"Kazakh\",\"km\":\"Khmer\",\"kn\":\"Kannada\",\"ko\":\"Korean\",\"ky\":\"Kyrgyz\",\"la\":\"Latin\",\"lb\":\"Luxembourgish\",\"lo\":\"Lao\",\"lt\":\"Lithuanian\",\"lv\":\"Latvian\",\"mg\":\"Malagasy\",\"mhr\":\"Mari\",\"mi\":\"Maori\",\"mk\":\"Macedonian\",\"ml\":\"Malayalam\",\"mn\":\"Mongolian\",\"mr\":\"Marathi\",\"mrj\":\"Hill Mari\",\"ms\":\"Malay\",\"mt\":\"Maltese\",\"my\":\"Burmese\",\"ne\":\"Nepali\",\"nl\":\"Dutch\",\"no\":\"Norwegian\",\"pa\":\"Punjabi\",\"pap\":\"Papiamento\",\"pl\":\"Polish\",\"pt\":\"Portuguese\",\"ro\":\"Romanian\",\"ru\":\"Russian\",\"si\":\"Sinhalese\",\"sk\":\"Slovak\",\"sl\":\"Slovenian\",\"sq\":\"Albanian\",\"sr\":\"Serbian\",\"su\":\"Sundanese\",\"sv\":\"Swedish\",\"sw\":\"Swahili\",\"ta\":\"Tamil\",\"te\":\"Telugu\",\"tg\":\"Tajik\",\"th\":\"Thai\",\"tl\":\"Tagalog\",\"tr\":\"Turkish\",\"tt\":\"Tatar\",\"udm\":\"Udmurt\",\"uk\":\"Ukrainian\",\"ur\":\"Urdu\",\"uz\":\"Uzbek\",\"vi\":\"Vietnamese\",\"xh\":\"Xhosa\",\"yi\":\"Yiddish\",\"zh\":\"Chinese\"";
    public static final String LANGS_RU = "\"af\":\"Африкаанс\",\"am\":\"Амхарский\",\"ar\":\"Арабский\",\"az\":\"Азербайджанский\",\"ba\":\"Башкирский\",\"be\":\"Белорусский\",\"bg\":\"Болгарский\",\"bn\":\"Бенгальский\",\"bs\":\"Боснийский\",\"ca\":\"Каталанский\",\"ceb\":\"Себуанский\",\"cs\":\"Чешский\",\"cy\":\"Валлийский\",\"da\":\"Датский\",\"de\":\"Немецкий\",\"el\":\"Греческий\",\"en\":\"Английский\",\"eo\":\"Эсперанто\",\"es\":\"Испанский\",\"et\":\"Эстонский\",\"eu\":\"Баскский\",\"fa\":\"Персидский\",\"fi\":\"Финский\",\"fr\":\"Французский\",\"ga\":\"Ирландский\",\"gd\":\"Шотландский (гэльский)\",\"gl\":\"Галисийский\",\"gu\":\"Гуджарати\",\"he\":\"Иврит\",\"hi\":\"Хинди\",\"hr\":\"Хорватский\",\"ht\":\"Гаитянский\",\"hu\":\"Венгерский\",\"hy\":\"Армянский\",\"id\":\"Индонезийский\",\"is\":\"Исландский\",\"it\":\"Итальянский\",\"ja\":\"Японский\",\"jv\":\"Яванский\",\"ka\":\"Грузинский\",\"kk\":\"Казахский\",\"km\":\"Кхмерский\",\"kn\":\"Каннада\",\"ko\":\"Корейский\",\"ky\":\"Киргизский\",\"la\":\"Латынь\",\"lb\":\"Люксембургский\",\"lo\":\"Лаосский\",\"lt\":\"Литовский\",\"lv\":\"Латышский\",\"mg\":\"Малагасийский\",\"mhr\":\"Марийский\",\"mi\":\"Маори\",\"mk\":\"Македонский\",\"ml\":\"Малаялам\",\"mn\":\"Монгольский\",\"mr\":\"Маратхи\",\"mrj\":\"Горномарийский\",\"ms\":\"Малайский\",\"mt\":\"Мальтийский\",\"my\":\"Бирманский\",\"ne\":\"Непальский\",\"nl\":\"Голландский\",\"no\":\"Норвежский\",\"pa\":\"Панджаби\",\"pap\":\"Папьяменто\",\"pl\":\"Польский\",\"pt\":\"Португальский\",\"ro\":\"Румынский\",\"ru\":\"Русский\",\"si\":\"Сингальский\",\"sk\":\"Словацкий\",\"sl\":\"Словенский\",\"sq\":\"Албанский\",\"sr\":\"Сербский\",\"su\":\"Сунданский\",\"sv\":\"Шведский\",\"sw\":\"Суахили\",\"ta\":\"Тамильский\",\"te\":\"Телугу\",\"tg\":\"Таджикский\",\"th\":\"Тайский\",\"tl\":\"Тагальский\",\"tr\":\"Турецкий\",\"tt\":\"Татарский\",\"udm\":\"Удмуртский\",\"uk\":\"Украинский\",\"ur\":\"Урду\",\"uz\":\"Узбекский\",\"vi\":\"Вьетнамский\",\"xh\":\"Коса\",\"yi\":\"Идиш\",\"zh\":\"Китайский\"";
}
